@startuml

(*)  -->[Вхід в програму через клас Main] "Створення нової гри
 new  Model, new Controller, new View"

--> "Візуалізація гри через
клас View та JFrame"
--> "ff"



If "Введення коменди з клавіатуури" then


--> [Yes] "Зміщення  існуючих плиток в напрямку "

else
--> "ssss"
else
--> "ssssss"
else


--> "Отриманна команда Esc"
-->(*)
@enduml