@startuml
start
: Початок;

while (натиснення клавіши)

    if (натисненно одну з клавіш стрілок)
    : зміщення плиток;
    elseif( натисненно "A")
    : ефективнийго хід;
    elseif (нитисненно "R")
    : випадковий хід;
    elseif (нитичненно "Z")
     : хід назад;
    endif

    if(Гра закінчена)then (Зібрана плитка 2048)
    : Гра виграна;
    else (всі плитки заповнені)
    : Гру прогарно;
    endif
    stop

endWhile

:Esc;
stop




@enduml